name: Analysis

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */7 * * *'

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install Docker
        run: |
          docker pull unclecode/crawl4ai:basic-amd64
          docker run -d -p 11235:11235 unclecode/crawl4ai:basic-amd64
          curl http://localhost:11235/health
      - name: Install Requirements 
        run: |
           pip install -r requirements.txt
      - name: Run Script 
        run: |
             python run.py
          
